### PR TITLE
Support typecast

### PR DESCRIPTION
**Pull request by sonots**
Added `default_typecast` and `typecast` options to support type casting from various types to various types. `column_options` which supports conversion only from String to boolean, long, double was deprecated.

To keep compatibility with lower versions, the default_typecast is true as default, and `column_options` are still available with a deprecation warning message.

```
src/main/java/org/embulk/parser/
└── jsonl
    ├── ColumnCaster.java
    ├── ColumnVisitorImpl.java
    ├── JsonRecordValidateException.java
    ├── JsonlParserPlugin.java
    └── cast
        ├── BooleanCast.java
        ├── DoubleCast.java
        ├── JsonCast.java
        ├── LongCast.java
        └── StringCast.java
```

Supporting typecast is useful in various cases although JSON itself has type of data such as boolean, integer, float, string. For example, Exporting BigQuery table with a JSON format dumps FLOAT column into integer (if decimal points are 0) or float (if decimal points are not 0). That is, types would be varying in each line.

To read such JSON text, we need to cast integer to float, and float to float (that is, no cast) automatically. This PR enables to do such parsing.

EDIT: I tried to make yaml configuration interface to be similar with parser-csv.
In parser csv, we write embulk types to cast in `columns` option (although these casts are all from String).
New interface allows us to write embulk types to cast in `columns` option similarly.

```
in:
  type: file
  path_prefix: "example/sample"
  parser:
    type: jsonl
    # default_typecast: true # default: true
    columns:
      - {name: "foo", type: "string"}
      - {name: "bool", type: "boolean"}
      - {name: "bool_str", type: "boolean"}
      - {name: "int", type: "long"}
      - {name: "int_str", type: "long"}
      - {name: "time", type: "timestamp", format: '%Y-%m-%d %H:%M:%S'}
      - {name: "double", type: "double"}
      - {name: "double_str", type: "double"}
      - {name: "array", type: "json"}
    stop_on_invalid_record: true
out:
  type: stdout
```

### CODE REVIEW

**Comment by sonots** [comment]
@muga ping cc: @shun0102 @joker1007

**Comment by joker1007** [comment]
This PR doesn't bother me. and code diff is LGTM.
it is better that plugin supports more type cast pattern. I think so.
But I have no idea for API design.

**Comment by muga** [comment]
Sorry for delay. I'm now in vacation (until the end of this month) and will check later. Sorry for your inconvenience..

**Comment by muga** [comment]
checking

**Comment by muga** [comment]
@sonots I roughly saw your PR. I agree with your config design and will accept and merge it. I have 2 comments now. 

a. Can you add unit tests for your change? You can see the test coverage rate by `$ ./gradlew clean test jacocoTestReport`.

b. I'm worry about the performance degradation cased by `if` statements that the type castings are using. Do you have any insight?

I will take a time later to read your PR more deeply and let you know if I have some questions.

**Comment by sonots** [comment]
Sure, I will write tests and do performance evaluation

**Comment by sonots** [comment]
`auto_typecast` branch was faster.

## Result of Performance Evaluation

machine spec:

```
CPU: Intel(R) Xeon(R) CPU X5650  @ 2.67GHz x 24
Memory: 12GB
```

sets of configs: 

see https://gist.github.com/sonots/7d33ef7d6c880f7f4dfc6ca6045f1b9a

## master branch without column_options

```
# time /usr/local/bin/embulk run -I lib /tmp/bench/config_old.yml
2016-05-28 17:32:51.170 +0900: Embulk v0.8.8
2016-05-28 17:32:52.723 +0900 [INFO] (0001:transaction): Loaded plugin embulk/parser/jsonl from a load path
2016-05-28 17:32:52.744 +0900 [INFO] (0001:transaction): Listing local files at directory '/tmp/bench' filtering filename by prefix 'sample'
2016-05-28 17:32:52.748 +0900 [INFO] (0001:transaction): Loading files [/tmp/bench/sample.jsonl]
2016-05-28 17:32:52.805 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=48 / output tasks 24 = input tasks 1 * 24
2016-05-28 17:32:52.808 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2016-05-28 17:34:00.572 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2016-05-28 17:34:00.579 +0900 [INFO] (main): Committed.
2016-05-28 17:34:00.580 +0900 [INFO] (main): Next config diff: {"in":{"last_path":"/tmp/bench/sample.jsonl"},"out":{}}

real    1m13.078s
user    1m37.190s
sys     0m4.284s
```

## master branch with column_options

```
# time /usr/local/bin/embulk run -I lib /tmp/bench/column_options.yml
2016-05-28 17:34:32.879 +0900: Embulk v0.8.8
2016-05-28 17:34:34.419 +0900 [INFO] (0001:transaction): Loaded plugin embulk/parser/jsonl from a load path
2016-05-28 17:34:34.440 +0900 [INFO] (0001:transaction): Listing local files at directory '/tmp/bench' filtering filename by prefix 'sample'
2016-05-28 17:34:34.444 +0900 [INFO] (0001:transaction): Loading files [/tmp/bench/sample.jsonl]
2016-05-28 17:34:34.503 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=48 / output tasks 24 = input tasks 1 * 24
2016-05-28 17:34:34.506 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2016-05-28 17:35:44.461 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2016-05-28 17:35:44.468 +0900 [INFO] (main): Committed.
2016-05-28 17:35:44.468 +0900 [INFO] (main): Next config diff: {"in":{"last_path":"/tmp/bench/sample.jsonl"},"out":{}}

real    1m15.239s
user    1m42.549s
sys     0m4.288s
```

## auto_typecast branch without typecast

```
# time /usr/local/bin/embulk run -I lib /tmp/bench/config_without_typecast.yml
2016-05-28 17:23:46.256 +0900: Embulk v0.8.8
2016-05-28 17:23:47.838 +0900 [INFO] (0001:transaction): Loaded plugin embulk/parser/jsonl from a load path
2016-05-28 17:23:47.862 +0900 [INFO] (0001:transaction): Listing local files at directory '/tmp/bench' filtering filename by prefix 'sample'
2016-05-28 17:23:47.866 +0900 [INFO] (0001:transaction): Loading files [/tmp/bench/sample.jsonl]
2016-05-28 17:23:47.928 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=48 / output tasks 24 = input tasks 1 * 24
2016-05-28 17:23:47.931 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2016-05-28 17:24:54.775 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2016-05-28 17:24:54.782 +0900 [INFO] (main): Committed.
2016-05-28 17:24:54.783 +0900 [INFO] (main): Next config diff: {"in":{"last_path":"/tmp/bench/sample.jsonl"},"out":{}}

real    1m12.245s
user    1m38.212s
sys     0m4.296s
```

## auto_typecast branch with typecast

```
# time /usr/local/bin/embulk run -I lib /tmp/bench/config_typecast.yml
2016-05-28 17:22:24.748 +0900: Embulk v0.8.8
2016-05-28 17:22:26.298 +0900 [INFO] (0001:transaction): Loaded plugin embulk/parser/jsonl from a load path
2016-05-28 17:22:26.321 +0900 [INFO] (0001:transaction): Listing local files at directory '/tmp/bench' filtering filename by prefix 'sample'
2016-05-28 17:22:26.324 +0900 [INFO] (0001:transaction): Loading files [/tmp/bench/sample.jsonl]
2016-05-28 17:22:26.384 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=48 / output tasks 24 = input tasks 1 * 24
2016-05-28 17:22:26.387 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2016-05-28 17:23:34.107 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2016-05-28 17:23:34.115 +0900 [INFO] (main): Committed.
2016-05-28 17:23:34.116 +0900 [INFO] (main): Next config diff: {"in":{"last_path":"/tmp/bench/sample.jsonl"},"out":{}}

real    1m13.020s
user    1m40.464s
sys     0m4.305s
```

**Comment by sonots** [comment]
@muga I added test codes and wrote results of performance evaluation above.

**Comment by muga** [comment]
@sonots 👍 

thank you for measuring. I will merge this PR and release new version (v0.2.0) after checking your test code.

**Comment by muga** [comment]
released new version v0.2.0 https://rubygems.org/gems/embulk-parser-jsonl/versions/0.2.0

cc: @sonots @shun0102

**Pull request merged**
