### PR TITLE
Enable cast string

### PR DESCRIPTION
**Pull request by joker1007**
Even If json value is string, read as long, double, boolean.

### CODE REVIEW

**Comment by muga** [comment]
@joker1007 sorry for the late response. I didn't notice your PR. 

I think that this type conversion is out of scope of the plugin's required feature, but it's better to support config option (maybe it's a flag) for this conversion. If you can resend the PR for support the option, it would be appreciated. Or if you have any concerns and your thoughts, please let us know.

**Comment by joker1007** [comment]
@muga Thanks for comment.
Is config option style like following ?
For example, it is case that parser parses string json value as long.

``` yml
in:
  type: file
  path_prefix: "sample"
  parser:
    type: jsonl
    columns:
      - {name: "foo", type: "string", as: "long"}                           # suggestion 1
      - {name: "other_style", type: "string", convert_to: "long"} # suggestion 2
      - {name: "other_style2", type: "long", from_string: true}   # suggestion 3

```

My thought is maybe wrong, Please advise me.

**Comment by muga** [comment]
@joker1007  Just in case, my expectation was `column_options` like style provided by https://github.com/embulk/embulk-input-jdbc like following:

```
  column_options:
    col1: {type: long}
    col3: {type: string, timestamp_format: "%Y/%m/%d", timezone: "+0900"}
```

Basically up to you and your implementation (I think that your ideas 1 and 2 might be able to work fine). But users sometimes require such kinds of type conversions in input plugins. We probably should standardize them as common feature. If so, `column_options` option is near standard. Because embulk-input-jdbc has been maintained on github.com/embulk:-p

**Comment by muga** [comment]
> (maybe it's a flag)

Ah, sorry. I noticed that the above comment confused you..

**Comment by joker1007** [comment]
Thanks!

```
  column_options:
    col1: {type: long}
    col3: {type: string, timestamp_format: "%Y/%m/%d", timezone: "+0900"}
```

it means that DATETIME or DATE or TIME column convert to string by `timestamp_format`, doesn't it?
But I want to convert some pattern strings (ex.  `"42"`, `"1.8"`) to `long` or `float` or etc.
I cannot imagine config format like `timestamp_format`.

As a other solution, filter plugin can convert column type.
But I think, it is more efficient that parser plugin parses directly.

**Comment by muga** [comment]
@joker1007 sorry for your confused again. The `col3` is not good example in this case. But the `col1` is still good example. The implementation makes sense, doesn't it? I think that it's same implementation as your 1st and 2nd ideas'.
https://github.com/embulk/embulk-input-jdbc/blob/0ff12c7048d5bc87df7a555f76ff47350e4c7717/embulk-input-jdbc/src/main/java/org/embulk/input/jdbc/AbstractJdbcInputPlugin.java#L173
https://github.com/embulk/embulk-input-jdbc/blob/0ff12c7048d5bc87df7a555f76ff47350e4c7717/embulk-input-jdbc/src/main/java/org/embulk/input/jdbc/getter/AbstractColumnGetter.java

To be clarified, we don't need to implement `{type: string}`, `{type: json}`, etc,.. for any column types for now. We can implement `{type: long}` and `{type: float}` for string type only. If other users or developers want other type conversions for other types in near future, we implement them at that time. 

> As a other solution, filter plugin can convert column type.
> But I think, it is more efficient that parser plugin parses directly.

Totally agree with you:-) I really want you to implement this feature in this plugin.

**Comment by joker1007** [comment]
@muga 
Thanks for your explanation :smile: 
I thought that I had understood that.

I re-implemented this feature and pushed commits.

``` yml
in:
  type: file
  path_prefix: "sample"
  parser:
    type: jsonl
    columns:
      - {name: "foo", type: "string"}
      - {name: "bool", type: "boolean"}
      - {name: "bool_str", type: "string"}
      - {name: "int", type: "long"}
      - {name: "int_str", type: "string"}
      - {name: "time", type: "timestamp", format: '%Y-%m-%d %H:%M:%S'}
      - {name: "double", type: "double"}
      - {name: "double_str", type: "string"}
      - {name: "array", type: "json"}
    column_options:
      bool_str: {type: "boolean"}
      int_str: {type: "long"}
      double_str: {type: "double"}
```

`columns` defines json column type, `column_options` defines embulk column type.
I think that it is near standard of embulk plugins.
How about this implementation?

**Comment by muga** [comment]
@joker1007 Cool, the design is what I expected:-) And the implementation also looks good to me. Can you add some unit tests for confirming the behavior of this option?

**Comment by joker1007** [comment]
@muga 
I wrote new test case for `column_options`. Is it enough?

**Comment by muga** [comment]
merged. thank you! :+1:

**Comment by muga** [comment]
@joker1007 And I released v0.1.2 cc: @shun0102 
https://rubygems.org/gems/embulk-parser-jsonl/versions/0.1.2

Thank you again.

**Pull request merged**
